import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import Navbar from "../components/Navbar";
import ThemePicker, { theme } from "../components/ThemePicker";
import App from "../public/templates/default";

type config = {
  title: string;
  description: string;
  theme: theme;
};

export default function Editor() {
  const [currentTheme, setCurrentTheme] = useState<theme>("light");
  const [title, setTitle] = useState<string>("My Awesome Website");
  const [description, setDescription] = useState<string>("");
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="drawer drawer-mobile">
        <input id="sidebar" type="checkbox" className="drawer-toggle" />
        <div className="drawer-content">
          <div className="mockup-window border bg-base-300 m-8">
            <div data-theme={currentTheme}>
              <App config={{ title, theme: currentTheme, description }} />
            </div>
          </div>
        </div>
        <div className="drawer-side">
          <label htmlFor="sidebar" className="drawer-overlay"></label>
          <ul className="menu p-4 w-80 bg-base-200 text-base-content">
            <input
              type="text"
              placeholder="My Awesome Website"
              className="input input-bordered input-secondary w-full max-w-xs mb-4"
              onChange={(e) => setTitle(e.target.value)}
            />
            <textarea
              className="textarea mb-4"
              placeholder="Description"
              onChange={(e) => setDescription(e.target.value)}
            ></textarea>
            <ThemePicker
              currentTheme={currentTheme}
              setCurrentTheme={setCurrentTheme}
            />
            <li>
              <a>Sidebar Item 2</a>
            </li>
            <div className="divider"></div>
            <li className="bg-primary rounded-btn text-primary-content">
              <a className="w-full place-content-center">Download</a>
            </li>
          </ul>
        </div>
      </div>
    </>
  );
}
