import Head from "next/head";
import Image from "next/image";
import Navbar from "../public/templates/navbar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mockup-window border bg-base-300 m-8">
        <div data-theme="halloween">
          <Navbar />
        </div>
        <div className="w-full h-12 bg-base-300 flex flex-row-reverse">
          <button className="btn btn-secondary rounded-none">Download</button>
        </div>
      </div>
    </>
  );
}
